const actions = {
  SET_LOAD_PAGE: 'SET_LOAD_PAGE',
  SET_TABLE_STATUS: 'SET_TABLE_STATUS',
  SET_BTN_TXT: 'SET_BTN_TXT',
  SET_TABLE_DATA: 'SET_TABLE_DATA',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SET_SEARCH_ID: 'SET_SEARCH_ID',
  SET_FILTERED_DATA: 'SET_FILTERED_DATA',
  SET_CHECKBOX_IS_CHECKED: 'SET_CHECKBOX_IS_CHECKED',
  SET_INPUT_DISABLE: 'SET_INPUT_DISABLE',
  TOGGLE_CHECKBOX_IS_CHECKED: 'TOGGLE_CHECKBOX_IS_CHECKED',
  TOGGLE_INPUT_DISABLE: 'TOGGLE_INPUT_DISABLE'

};

export default actions;
